### ISSUE TITLE
Errores al ejecutar manage.py

### ISSUE THREAD

**Issue by yoadimpen** [yoadimpen/EGC-1530-yoadimpen#1]
Descripcion: Al ejecutar `./manage.py migrate`, `./manage.py runserver` o cualquier comando que involucre al archivo manage.py salta la siguiente traza de error en la que se indica que no se encuentra un local_settings.py y tampoco es capaz de encontrar el paquete path:

```
local_settings.py not found
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/management/base.py", line 361, in check
    all_issues = self._run_checks(
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yoadimpen/ev/lib/python3.8/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yoadimpen/UNI/exam_ant/1530/EGC-1530-yoadimpen/decide/decide/urls.py", line 25, in <module>
    path('admin/', admin.site.urls),
NameError: name 'path' is not defined
```

Para replicar el error: Al entrar en la carpeta decide con `cd decide` ejecutar `./manage.py migrate`. Es posible que primero salte un mensaje en el que se indique que se deniega el permiso para trabajar con manage.py. En ese caso se debe ejecutar primero `chmod +x manage.py`.

Comportamiento que debería tener: Al ejecutar `./manage.py migrate`, `./manage.py runserver` o cualquier comando que inlcuya manage.py en alguno de sus pasos debería tener una salida exitosa. En este caso al hacer por ejemplo `./manage.py runserver` debería levantar el servidor sin problema.

**Comment by yoadimpen** [comment]
Al descomentar las líneas 17 y 18 del archivo /decide/decide/urls.py se ha podido encontrar el paquete path en la ejecución, falta el local_settings.py
